name: Generate GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual runs

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AvgoustisW
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Athens
